version: '3.7'

services:

  frontend:
    image: 'muharlyamovy/front:latest'
    build: ./
    container_name: front
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
