export const Types = {
    //Markets
    GET_MARKETS_TYPES: 'GET_MARKETS_TYPES',
    GET_RANDOM_MARKETS: 'GET_RANDOM_MARKETS',
    GET_MAIN_MARKETS: 'GET_MAIN_MARKETS',
    GET_MARKET_PAGE_DATA: 'GET_MARKET_PAGE_DATA',
    GET_MARKET_PAGE_GOODS: 'GET_MARKET_PAGE_GOODS',

    //Auth
    AUTH_TRUE: 'AUTH_TRUE',
    AUTH_TOKEN_ID: 'AUTH_TOKEN_ID'
};