export const Types = {
    //Auth
    AUTH_TRUE: 'AUTH_TRUE',
    AUTH_TOKEN_ID: 'AUTH_TOKEN_ID',
    GET_PROFILE_DATA: 'GET_PROFILE_DATA',
    ClEAR_ALL_STATE: 'ClEAR_ALL_STATE',

    //Loader
    LOADER_TRUE: 'LOADER_TRUE',
    LOADER_FALSE: 'LOADER_FALSE',

    //Markets
    GET_MARKETS_TYPES: 'GET_MARKETS_TYPES',
    GET_RANDOM_MARKETS: 'GET_RANDOM_MARKETS',
    GET_MARKETS: 'GET_MARKETS',
    GET_MARKET_PAGE_DATA: 'GET_MARKET_PAGE_DATA',
    GET_MARKET_PAGE_GOODS: 'GET_MARKET_PAGE_GOODS',
    GET_USER_MARKET: 'GET_USER_MARKET',

    //Goods
    GET_GOODS_TYPES: 'GET_GOODS_TYPES',
    GET_GOODS: 'GET_GOODS',
    GET_GOOD_PAGE_DATA: 'GET_GOOD_PAGE_DATA',
    GET_USER_GOODS: 'GET_USER_GOODS',

    //Cart
    GET_CART: 'GET_CART',

    //RECOMMENDATION
    GET_RECOMMENDATION: 'GET_RECOMMENDATION',

    //FAVORITES
    GET_FAVORITES: 'GET_FAVORITES'



};